image: node:10

cache:
  paths:
    - node_modules/
    - .yarn
before_script:
  - yarn config set cache-folder .yarn
  - yarn install

Lint:
  script: yarn lint

Build:
  script: NODE_ENV=production yarn build
