version: 2
jobs:
  build:
    branches:
      only:
        - dev
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy
          command: |
              set -e
              npm install
              CI="" npm run build

              remote=$(git config remote.origin.url)

              siteSource="out"

              if [ ! -d "$siteSource" ]
              then
                  echo "Usage: $0 <site source dir>"
                  exit 1
              fi

              mkdir master-branch
              cd master-branch
              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
              git config --global user.name "$GH_NAME" > /dev/null 2>&1
              git init
              git remote add --fetch origin "$remote"

              if git rev-parse --verify origin/master > /dev/null 2>&1
              then
                  git checkout master
                  git rm -rf .
              else
                  git checkout --orphan master
              fi

              cp -a "../${siteSource}/." .
              touch .nojekyll

              git add -A
              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
              git push --force --quiet origin master > /dev/null 2>&1

              cd ..
              rm -rf master-branch

              echo "Finished Deployment!"
